---

- name: Installing packages
  yum: name={{ item }} state=present
  with_items:
   - unzip
   - glibc.i686
   - libgcc.i686
   - libstdc++.i686

- name: Disable iptables
  service: name=iptables state=stopped enabled=false
  service: name=ip6tables state=stopped enabled=false

- name: Create domino group
  group: name={{ domino_group }} state=present

- name: Create domino user
  user: uid={{ domino_uid }} name={{ domino_user }} group={{ domino_group }}

- name: Create installer directory
  file: path='{{ domino_installation_path }}' state=directory

- name: Create notesdata directory
  file: path='{{ domino_data_path }}' state=directory

- name: Download Domino installer
  get_url: url={{ domino_installation_archive }} dest={{ domino_installation_path }}.tar

- name: Unpack Domino installer
  unarchive: src={{ domino_installation_path }}.tar dest={{ domino_installation_path }} copy=no creates={{ domino_installation_path }}/linux64/DominoEval/install

- name: Copy response file
  template: src=response.dat.j2 dest={{ domino_installation_path }}/response.dat mode=0755

- name: Copy answer file
  copy: src=domino.pds dest={{ domino_installation_path }}/domino.pds mode=0755

- name: Install Domino server
  shell: "{{ domino_installation_path }}/linux64/DominoEval/install -silent -options {{ domino_installation_path }}/response.dat"
  args:
    creates: /opt/ibm/lotus/bin/server

- name: Copy configuration files
  template: src={{ item.path }} dest={{ item.dest }} mode=0755
  with_items:
    - { path: 'rc_domino.j2', dest: '/etc/init.d/rc_domino' }
    - { path: 'rc_domino_script.j2', dest: '/opt/ibm/lotus/rc_domino_script' }
    - { path: 'rc_domino_config_domino.j2', dest: '/etc/sysconfig/rc_domino_config_{{ domino_user }}' }

- name: Set OS limits
  lineinfile: dest=/etc/security/limits.conf insertbefore='# End of file' line='domino           {{ item.type }}    nofile          {{ item.value }}'
  with_items:
      - { type: 'soft', value: '60000'}
      - { type: 'hard', value: '80000'}

- name: Configure Domino data
  sudo: true
  sudo_user: "{{ domino_user }}"
  shell: /opt/ibm/lotus/bin/server -silent {{ domino_installation_path }}/domino.pds
  args:
    chdir: "{{ domino_data_path }}"
    creates: "{{ domino_data_path }}/names.nsf"

- name: Enable and start Domino server
  service: name=rc_domino state=started enabled=yes
